# Generated by Django 5.0.4 on 2024-05-03 16:36

import datetime
import django.db.models.deletion
import django.utils.timezone
import realestatepro.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('leidc', models.CharField(default=realestatepro.models.Cliente.generate_custom_id, max_length=20, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('telefone', models.CharField(blank=True, max_length=15)),
                ('morada', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Mediador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('telefone', models.CharField(blank=True, max_length=15)),
                ('morada', models.CharField(blank=True, max_length=100)),
                ('nif', models.IntegerField(blank=True, null=True)),
                ('iban', models.CharField(blank=True, max_length=34)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mediador',
                'verbose_name_plural': 'Mediadores',
            },
        ),
        migrations.CreateModel(
            name='Propriedade',
            fields=[
                ('id', models.CharField(default=realestatepro.models.Propriedade.generate_custom_id, max_length=10, primary_key=True, serialize=False)),
                ('natureza', models.CharField(choices=[('Escritório', 'Escritório'), ('Herdade', 'Herdade'), ('Armazém', 'Armazém'), ('Casa Antiga', 'Casa Antiga'), ('Bloco de apartamentos', 'Bloco de apartamentos'), ('Residencial', 'Residencial'), ('Apartamento', 'Apartamento'), ('Moradia', 'Moradia')], max_length=50)),
                ('disponibilidade', models.CharField(blank=True, choices=[('Retirado', 'Retirado'), ('Reservado', 'Reservado'), ('Vendido', 'Vendido'), ('Disponível', 'Disponível')], max_length=50)),
                ('estado', models.CharField(blank=True, choices=[('Recuperado', 'Recuperado'), ('Por recuperar', 'Por recuperar'), ('Em construção', 'Em construção'), ('Renovado', 'Renovado'), ('Novo', 'Novo')], max_length=150)),
                ('titulo', models.CharField(blank=True, max_length=150)),
                ('descricao', models.TextField(blank=True, max_length=150)),
                ('quartos', models.IntegerField(blank=True, null=True)),
                ('area_privativa_bruta', models.IntegerField(blank=True, null=True)),
                ('area_util', models.IntegerField(blank=True, null=True)),
                ('preco', models.IntegerField(blank=True, null=True)),
                ('ano_construcao', models.IntegerField(blank=True, default=datetime.datetime(2024, 5, 3, 16, 36, 14, 943235, tzinfo=datetime.timezone.utc), null=True)),
                ('contrato_mediacao', models.CharField(blank=True, max_length=100)),
                ('morada', models.CharField(blank=True, max_length=100)),
                ('codigo_postal', models.CharField(blank=True, max_length=10)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('piso', models.CharField(blank=True, max_length=10)),
                ('fracao', models.CharField(blank=True, max_length=10)),
                ('distrito', models.CharField(blank=True, max_length=50)),
                ('concelho', models.CharField(blank=True, max_length=50)),
                ('freguesia', models.CharField(blank=True, max_length=50)),
                ('zona', models.CharField(blank=True, max_length=50)),
                ('certificado_energetico', models.CharField(blank=True, max_length=100)),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('mediador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propriedades_criadas', to='realestatepro.mediador')),
                ('venda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='realestatepro.cliente')),
            ],
            options={
                'ordering': ['-criacao'],
            },
        ),
        migrations.CreateModel(
            name='Proposta',
            fields=[
                ('id_proposta', models.AutoField(primary_key=True, serialize=False)),
                ('data_proposta', models.DateField(default=django.utils.timezone.now)),
                ('valor', models.IntegerField()),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propostas_feitas', to='realestatepro.cliente')),
                ('propriedade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realestatepro.propriedade')),
            ],
            options={
                'ordering': ['-criacao'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='images/')),
                ('propriedade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='realestatepro.propriedade')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='files/')),
                ('propriedade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='realestatepro.propriedade')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('youtube_link', models.URLField()),
                ('propriedade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='realestatepro.propriedade')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id_visita', models.AutoField(primary_key=True, serialize=False)),
                ('data_visita', models.DateField(default=django.utils.timezone.now)),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas_efetuadas', to='realestatepro.cliente')),
                ('propriedade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realestatepro.propriedade')),
            ],
            options={
                'ordering': ['-criacao'],
            },
        ),
    ]
