# Generated by Django 5.0.4 on 2024-05-02 15:03

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('leidc', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('telefone', models.CharField(blank=True, max_length=15)),
                ('morada', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Mediador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('telefone', models.CharField(blank=True, max_length=15)),
                ('morada', models.CharField(blank=True, max_length=100)),
                ('nif', models.IntegerField(blank=True, null=True)),
                ('iban', models.CharField(blank=True, max_length=34)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mediador',
                'verbose_name_plural': 'Mediadores',
            },
        ),
        migrations.CreateModel(
            name='Propriedade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('disponibilidade', models.CharField(blank=True, choices=[('Retirado', 'Retirado'), ('Reservado', 'Reservado'), ('Vendido', 'Vendido'), ('Disponível', 'Disponível')], max_length=50)),
                ('estado', models.CharField(blank=True, max_length=150)),
                ('natureza', models.CharField(choices=[('Escritório', 'Escritório'), ('Herdade', 'Herdade'), ('Armazém', 'Armazém'), ('Casa Antiga', 'Casa Antiga'), ('Bloco de apartamentos', 'Bloco de apartamentos'), ('Residencial', 'Residencial'), ('Apartamento', 'Apartamento'), ('Moradia', 'Moradia')], max_length=50)),
                ('titulo', models.CharField(blank=True, max_length=150)),
                ('descricao', models.CharField(blank=True, max_length=150)),
                ('quartos', models.IntegerField(blank=True, null=True)),
                ('area_privativa_bruta', models.IntegerField(blank=True, null=True)),
                ('area_util', models.IntegerField(blank=True, null=True)),
                ('preco', models.IntegerField(blank=True, null=True)),
                ('ano_construcao', models.IntegerField(blank=True, default=datetime.datetime(2024, 5, 2, 15, 3, 36, 355866, tzinfo=datetime.timezone.utc), null=True)),
                ('contrato_mediacao', models.CharField(blank=True, max_length=100)),
                ('morada', models.CharField(blank=True, max_length=100)),
                ('codigo_postal', models.CharField(blank=True, max_length=10)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('piso', models.CharField(blank=True, max_length=10)),
                ('fracao', models.CharField(blank=True, max_length=10)),
                ('distrito', models.CharField(blank=True, max_length=50)),
                ('concelho', models.CharField(blank=True, max_length=50)),
                ('freguesia', models.CharField(blank=True, max_length=50)),
                ('zona', models.CharField(blank=True, max_length=50)),
                ('certificado_energetico', models.CharField(blank=True, max_length=100)),
                ('imagens', models.FileField(blank=True, null=True, upload_to='media/images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='media/videos/')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('mediador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propriedades_criadas', to='realestatepro.mediador')),
                ('venda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='realestatepro.cliente')),
            ],
            options={
                'ordering': ['-criacao'],
            },
        ),
        migrations.CreateModel(
            name='Proposta',
            fields=[
                ('id_proposta', models.AutoField(primary_key=True, serialize=False)),
                ('data_proposta', models.DateField(default=django.utils.timezone.now)),
                ('valor', models.IntegerField()),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propostas_feitas', to='realestatepro.cliente')),
                ('propriedade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realestatepro.propriedade')),
            ],
            options={
                'ordering': ['-criacao'],
            },
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id_visita', models.AutoField(primary_key=True, serialize=False)),
                ('data_visita', models.DateField()),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas_efetuadas', to='realestatepro.cliente')),
                ('propriedade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realestatepro.propriedade')),
            ],
            options={
                'ordering': ['-criacao'],
            },
        ),
    ]
