# Generated by Django 5.0.4 on 2024-05-04 21:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestatepro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propriedade',
            name='ano_construcao',
            field=models.IntegerField(blank=True, default=datetime.datetime(2024, 5, 4, 21, 56, 13, 24036, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
