# Generated by Django 5.0.4 on 2024-05-03 16:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestatepro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='description',
        ),
        migrations.RemoveField(
            model_name='image',
            name='description',
        ),
        migrations.RemoveField(
            model_name='video',
            name='description',
        ),
        migrations.AlterField(
            model_name='propriedade',
            name='ano_construcao',
            field=models.IntegerField(blank=True, default=datetime.datetime(2024, 5, 3, 16, 55, 5, 584214, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
