# Generated by Django 5.0.4 on 2024-05-03 22:42

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestatepro', '0002_remove_file_description_remove_image_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='propriedade',
        ),
        migrations.RemoveField(
            model_name='video',
            name='propriedade',
        ),
        migrations.AlterField(
            model_name='propriedade',
            name='ano_construcao',
            field=models.IntegerField(blank=True, default=datetime.datetime(2024, 5, 3, 22, 42, 19, 891874, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='propriedade',
            name='natureza',
            field=models.CharField(blank=True, choices=[('Escritório', 'Escritório'), ('Herdade', 'Herdade'), ('Armazém', 'Armazém'), ('Casa Antiga', 'Casa Antiga'), ('Bloco de apartamentos', 'Bloco de apartamentos'), ('Residencial', 'Residencial'), ('Apartamento', 'Apartamento'), ('Moradia', 'Moradia')], max_length=50),
        ),
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('imagem', 'Imagem'), ('video', 'Vídeo'), ('arquivo', 'Arquivo')], max_length=20)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('video', models.URLField(blank=True, null=True)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='files/')),
                ('propriedade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realestatepro.propriedade')),
            ],
        ),
        migrations.DeleteModel(
            name='File',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
