# Generated by Django 5.0.4 on 2024-05-02 15:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestatepro', '0003_alter_propriedade_ano_construcao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propriedade',
            name='ano_construcao',
            field=models.IntegerField(blank=True, default=datetime.datetime(2024, 5, 2, 15, 34, 32, 182716, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='propriedade',
            name='id',
            field=models.CharField(default='', max_length=10, primary_key=True, serialize=False),
        ),
    ]
