# Generated by Django 5.0.4 on 2024-05-04 22:03

import datetime
import realestatepro.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestatepro', '0003_alter_propriedade_ano_construcao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['-nome']},
        ),
        migrations.AlterField(
            model_name='cliente',
            name='leidc',
            field=models.CharField(default=realestatepro.models.Cliente.generate_custom_id, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='propriedade',
            name='ano_construcao',
            field=models.IntegerField(blank=True, default=datetime.datetime(2024, 5, 4, 22, 3, 33, 33917, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
