# Generated by Django 5.0.4 on 2024-05-03 22:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestatepro', '0003_remove_image_propriedade_remove_video_propriedade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propriedade',
            name='ano_construcao',
            field=models.IntegerField(blank=True, default=datetime.datetime(2024, 5, 3, 22, 48, 14, 972908, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
