# Generated by Django 5.0.4 on 2024-05-04 22:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestatepro', '0004_alter_cliente_options_alter_cliente_leidc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propriedade',
            name='ano_construcao',
            field=models.IntegerField(blank=True, default=datetime.datetime(2024, 5, 4, 22, 5, 24, 670911, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
