# Generated by Django 5.0.4 on 2024-05-02 16:16

import datetime
import realestatepro.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestatepro', '0006_alter_propriedade_ano_construcao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propriedade',
            name='ano_construcao',
            field=models.IntegerField(blank=True, default=datetime.datetime(2024, 5, 2, 16, 16, 58, 408545, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='propriedade',
            name='descricao',
            field=models.TextField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='propriedade',
            name='id',
            field=models.CharField(default=realestatepro.models.Propriedade.generate_custom_id, max_length=10, primary_key=True, serialize=False),
        ),
    ]
