# Generated by Django 5.0.4 on 2024-05-02 17:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestatepro', '0008_alter_propriedade_ano_construcao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propriedade',
            name='ano_construcao',
            field=models.IntegerField(blank=True, default=datetime.datetime(2024, 5, 2, 17, 22, 49, 941401, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
