# Generated by Django 5.0.4 on 2024-05-02 17:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestatepro', '0009_alter_propriedade_ano_construcao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propriedade',
            name='ano_construcao',
            field=models.IntegerField(blank=True, default=datetime.datetime(2024, 5, 2, 17, 33, 11, 299435, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='propriedade',
            name='estado',
            field=models.CharField(blank=True, choices=[('Recuperado', 'Recuperado'), ('Por recuperar', 'Por recuperar'), ('Em construção', 'Em construção'), ('Renovado', 'Renovado'), ('Novo', 'Novo')], max_length=150),
        ),
    ]
