# Generated by Django 5.0.4 on 2024-05-02 17:56

import datetime
import realestatepro.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestatepro', '0010_alter_propriedade_ano_construcao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='leidc',
            field=models.CharField(default=realestatepro.models.Cliente.generate_custom_id, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='propriedade',
            name='ano_construcao',
            field=models.IntegerField(blank=True, default=datetime.datetime(2024, 5, 2, 17, 56, 2, 803133, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
